---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbkraft
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  storageClassName: rbkraft
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
