# allow outbound for DNS and HTTP/S
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limited-egress
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP

# allow inbound to mavencraft from map
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mavencraft-allow-map
spec:
  podSelector:
    matchLabels:
      name: mavencraft
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: map

# allow outbound from map to mavencraft
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: map-allow-mavencraft
spec:
  podSelector:
    matchLabels:
      name: map
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: mavencraft
