---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbkraft
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rbkraft
  local:
    path: /var/tmp/rbkraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
          - linux
