---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: creative-world
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  storageClassName: async-gp2
  #selector:
  #  matchLabels:
  #    usage: "creative-world"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: creative-map
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  storageClassName: async-gp2
  #selector:
  #  matchLabels:
  #    usage: "creative-map"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mavencraft-creative-world-volume
#  labels:
#    usage: creative-world
#spec:
#  storageClassName: async-gp2
#  capacity:
#    storage: 30Gi
#  accessModes:
#    - ReadWriteOnce
#  awsElasticBlockStore:
#    fsType: ext4
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mavencraft-creative-map-volume
#  labels:
#    usage: creative-map
#spec:
#  storageClassName: async-gp2
#  capacity:
#    storage: 30Gi
#  accessModes:
#    - ReadWriteOnce
#  awsElasticBlockStore:
#    fsType: ext4
