---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: creative-world
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  storageClassName: async-gp2
  #selector:
  #  matchLabels:
  #    usage: "creative-world"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: creative-map
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  storageClassName: async-gp2
  #selector:
  #  matchLabels:
  #    usage: "creative-map"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
