---
- name: setup hostname according to inventory
  sudo: true
  hostname: name=mavencraft.net

- name: update and upgrade apt-get
  sudo: true
  apt: update_cache=true cache_valid_time=6000

- name: bootstrap python-apt package
  sudo: true
  command: apt-get -y --force-yes install -o APT::Immediate-Configure=false python-minimal python-apt lzma

- name: bootstrap apt package 2
  sudo: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  command: apt-get -y --force-yes upgrade

- name: ensure https support for apt is installed
  sudo: true
  apt: pkg=apt-transport-https state=present

#- shell: sudo apt-get remove ruby1.8 ruby1.8-dev unzip libreadline5 zip libruby1.8

- name: install main system packages
  apt: pkg={{ item }} state=latest
  sudo: true
  with_items:
    - apt-transport-https
    - vim
    - git
    - screen
    - ruby2.2
    - rake
    - openjdk-7-jre
    - python-imaging
    - python-numpy
    - nginx
    - htop
    - xinetd
    - cmake
    - libassimp-dev
    - m4
    - autoconf
    - libtool
    - libboost-dev
    - libboost-all-dev
    - libboost-thread-dev
    - libboost-filesystem-dev
    - libboost-test-dev


#- python-pil
#- liblapack3
#- libgfortran3
#- libwebp5
#- libwebpmux1


- name: fetch overviewer
  sudo: true
  get_url: url="http://overviewer.org/builds/deb64/11/overviewer-0.12.81.deb" dest=/var/tmp/ mode=0440 #sha256sum=8ac27182d9b5ee7c273ba37df871638f527546a929da0aa0d29be5c487e9e1c7

- name: install overviewer
  sudo: true
  shell: dpkg -i /var/tmp/overviewer-0.12.81.deb

- name: add mavencraft group
  sudo: true
  group: name=mavencraft state=present

- name: add mavencraft user
  sudo: true
  user: name=mavencraft state=present groups=mavencraft shell=/bin/bash

- name: install github ssh host key
  lineinfile: backup=true create=true dest=~/.ssh/known_hosts line="github.com,192.30.252.131 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" state=present

- name: home dir
  sudo: true
  file: dest=/home/mavencraft state=directory mode=777

- name: fix perms
  sudo: true
  shell: chown -Rv ubuntu:ubuntu /home/mavencraft/{{ item.dest }}
  with_items:
    - dest: mavencraft
    - dest: voxelizer
    - dest: voxelize-stl-xinetd
    - dest: fcl 
    - dest: libccd 

- name: required git repos for full mavencrafting
  git: update=true repo={{ item.repo }} dest=/home/mavencraft/{{ item.dest }} force=true
  with_items:
    - dest: mavencraft
      repo: git@github.com:mavenlink/mavencraft.git
    - dest: voxelizer
      repo: git@github.com:diclophis/voxelizer.git
    - dest: voxelize-stl-xinetd
      repo: git@github.com:diclophis/voxelize-stl-xinetd.git
    - dest: fcl
      repo: git@github.com:flexible-collision-library/fcl.git
    - dest: libccd 
      repo: git@github.com:danfis/libccd.git
    - dest: mapcrafter
      repo: git@github.com:mapcrafter/mapcrafter.git

- name: build deps
  sudo: true
  shell: "{{ item }}"
  with_items:
    - "cd /home/mavencraft/libccd && /home/mavencraft/libccd/bootstrap && mkdir -p /home/mavencraft/libccd/build && cd /home/mavencraft/libccd/build && /home/mavencraft/libccd/configure --prefix=/usr && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr /home/mavencraft/libccd && make -j 6 && make install"
    - "cd /home/mavencraft/fcl && mkdir -p /home/mavencraft/fcl/build && cd /home/mavencraft/fcl/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr /home/mavencraft/fcl && make -j 6 && make install"
    - "cd /home/mavencraft/voxelizer && mkdir -p /home/mavencraft/voxelizer/build && cd /home/mavencraft/voxelizer/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr /home/mavencraft/voxelizer && make -j 6"
    - "cd /home/mavencraft/mapcrafter && mkdir -p /home/mavencraft/mapcrafter/build && cd /home/mavencraft/mapcrafter/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr /home/mavencraft/mapcrafter && make -j 6"

- name: faster sync
  sudo: true
  synchronize: mode=push src="{{ item }}" dest="/home/mavencraft"
  with_items:
    - banned-ips.json
    - banned-players.json
    - mavencraft-bukkit.yml
    - minecraft-bukkit.yml
    - commands.yml
    - help.yml
    - ops.json
    - permissions.yml
    - server.properties
    - whitelist.json
    - xinetd
    - eula.txt
    - mapcrafter.conf
    - mapcrafter-log.conf

#- minecraft.jar
#- textures
#- plugins

- name: dir
  sudo: true
  file: dest=/usr/share/nginx/html state=directory owner=mavencraft group=root

- name: fix existing
  sudo: true
  shell: chown -Rv mavencraft:users /usr/share/nginx/html

- name: fix existing
  sudo: true
  shell: chown -Rv mavencraft:users /home/mavencraft

- name: fix existing
  sudo: true
  shell: chown -Rv ubuntu:users /home/mavencraft/mavencraft

- name: symlink start script
  sudo: true
  shell: rm -Rf /etc/xinetd.d/* && ln -sf /home/mavencraft/xinetd /etc/xinetd.d/mavencraft && /etc/init.d/xinetd restart

- name: install minecraft shell scripts
  sudo: true
  copy: src={{ item }} dest=/usr/bin/{{ item }} mode=777
  with_items:
    - minecraft.sh
    - minecraft-status.sh
    - minecraft-repair.sh

- name: install minecraft backup
  sudo: true
  file: dest=/home/mavencraft/backup state=directory

- name: fetch chunky
  get_url: url="http://chunkyupdate.llbit.se/ChunkyLauncher.jar" dest=~/

- name: update chunky
  shell: "java -jar ChunkyLauncher.jar --update"

- shell: "java -jar ChunkyLauncher.jar -download-mc 1.8.8"

#- shell: ~/.chunky/scenes
#- shell: "java -jar ~/ChunkyLauncher.jar -render SceneName"

- name: install voxelize stl daemon
  sudo: true
  copy: src=voxelizer.conf dest=/etc/init/voxelizer.conf

- name: restart voxelizer
  sudo: true
  service: name=voxelizer state=started enabled=true
